insert into autores (id, nome, nacionalidade, nascimento) values (1, 'Shaylynn Oattes', 'Vietnam', '12/07/1985');
insert into autores (id, nome, nacionalidade, nascimento) values (2, 'Nobe Franzotto', 'China', '20/04/1934');
insert into autores (id, nome, nacionalidade, nascimento) values (3, 'Claudell Burnel', 'Serbia', '29/06/1966');
insert into autores (id, nome, nacionalidade, nascimento) values (4, 'Doe Connock', 'Philippines', '28/06/1973');
insert into autores (id, nome, nacionalidade, nascimento) values (5, 'Torrey Verzey', 'Norway', '01/08/1950');
insert into autores (id, nome, nacionalidade, nascimento) values (6, 'Quent Ronchka', 'China', '20/08/1971');
insert into autores (id, nome, nacionalidade, nascimento) values (7, 'Cele Warwicker', 'Sweden', '26/04/1989');
insert into autores (id, nome, nacionalidade, nascimento) values (8, 'Simone Lagadu', 'South Sudan', '21/07/1976');
insert into autores (id, nome, nacionalidade, nascimento) values (9, 'Rodina Hatchette', 'Libya', '10/10/1984');
insert into autores (id, nome, nacionalidade, nascimento) values (10, 'Whittaker Lawtie', 'Indonesia', '09/10/1965');
insert into autores (id, nome, nacionalidade, nascimento) values (11, 'Tammie Readwin', 'Netherlands', '07/07/1981');
insert into autores (id, nome, nacionalidade, nascimento) values (12, 'Fionna Heintzsch', 'China', '19/11/1933');
insert into autores (id, nome, nacionalidade, nascimento) values (13, 'Clarey Jimeno', 'Uganda', '10/12/1981');
insert into autores (id, nome, nacionalidade, nascimento) values (14, 'Dulsea Allard', 'Ireland', '10/04/1991');
insert into autores (id, nome, nacionalidade, nascimento) values (15, 'Delaney Kynvin', 'Peru', '10/07/1910');
insert into autores (id, nome, nacionalidade, nascimento) values (16, 'Charmane Steet', 'United States', '27/09/1924');
insert into autores (id, nome, nacionalidade, nascimento) values (17, 'Massimo Medendorp', 'Indonesia', '10/06/1971');
insert into autores (id, nome, nacionalidade, nascimento) values (18, 'Helene Fleg', 'Mongolia', '09/04/1932');
insert into autores (id, nome, nacionalidade, nascimento) values (19, 'Sayre Gandley', 'Poland', '06/11/1992');
insert into autores (id, nome, nacionalidade, nascimento) values (20, 'Sallie Walshe', 'Indonesia', '21/04/1981');
insert into autores (id, nome, nacionalidade, nascimento) values (21, 'Garret Belt', 'Russia', '24/02/1977');
insert into autores (id, nome, nacionalidade, nascimento) values (22, 'Pearce Currie', 'Morocco', '15/06/1937');
insert into autores (id, nome, nacionalidade, nascimento) values (23, 'Kathlin Stoddart', 'Thailand', '22/11/1970');
insert into autores (id, nome, nacionalidade, nascimento) values (24, 'Florri Rhelton', 'Brazil', '12/01/1995');
insert into autores (id, nome, nacionalidade, nascimento) values (25, 'Fernande Adne', 'Russia', '13/01/1950');
insert into autores (id, nome, nacionalidade, nascimento) values (26, 'Faun Novkovic', 'Portugal', '29/08/1914');
insert into autores (id, nome, nacionalidade, nascimento) values (27, 'Hussein Worsam', 'Botswana', '15/06/1995');
insert into autores (id, nome, nacionalidade, nascimento) values (28, 'Garrek Romagosa', 'Philippines', '13/01/1970');
insert into autores (id, nome, nacionalidade, nascimento) values (29, 'Olia Robker', 'Indonesia', '28/06/1990');
insert into autores (id, nome, nacionalidade, nascimento) values (30, 'Harmonia Bostock', 'Indonesia', '02/10/1967');
insert into autores (id, nome, nacionalidade, nascimento) values (31, 'Danyelle Girke', 'Indonesia', '18/08/1956');
insert into autores (id, nome, nacionalidade, nascimento) values (32, 'Amalita Trayte', 'Indonesia', '29/05/1991');
insert into autores (id, nome, nacionalidade, nascimento) values (33, 'Ranice Scholtz', 'Costa Rica', '21/09/1938');
insert into autores (id, nome, nacionalidade, nascimento) values (34, 'Breena Mussard', 'Iran', '15/06/1943');
insert into autores (id, nome, nacionalidade, nascimento) values (35, 'Birgit Keller', 'Portugal', '03/02/1935');
insert into autores (id, nome, nacionalidade, nascimento) values (36, 'Valentino Hanmore', 'Colombia', '15/09/1988');
insert into autores (id, nome, nacionalidade, nascimento) values (37, 'Lucias Skep', 'China', '28/07/1964');
insert into autores (id, nome, nacionalidade, nascimento) values (38, 'Donielle Aldin', 'Russia', '27/07/1990');
insert into autores (id, nome, nacionalidade, nascimento) values (39, 'Cynthie Breissan', 'Philippines', '08/03/1930');
insert into autores (id, nome, nacionalidade, nascimento) values (40, 'Zerk Coverdale', 'Philippines', '12/03/1959');
insert into autores (id, nome, nacionalidade, nascimento) values (41, 'Jesus Bodham', 'United Kingdom', '14/09/1943');
insert into autores (id, nome, nacionalidade, nascimento) values (42, 'Jayne Applebee', 'Democratic Republic of the Congo', '13/07/1964');
insert into autores (id, nome, nacionalidade, nascimento) values (43, 'Frasier Maliphant', 'Canada', '16/06/1964');
insert into autores (id, nome, nacionalidade, nascimento) values (44, 'Edna Gowlett', 'Morocco', '18/03/1992');
insert into autores (id, nome, nacionalidade, nascimento) values (45, 'Ileane Smithen', 'Indonesia', '28/05/1998');
insert into autores (id, nome, nacionalidade, nascimento) values (46, 'Maurene Arnoll', 'France', '16/01/1914');
insert into autores (id, nome, nacionalidade, nascimento) values (47, 'Josiah Pyzer', 'Philippines', '01/08/1947');
insert into autores (id, nome, nacionalidade, nascimento) values (48, 'Gelya Deegan', 'Chile', '15/02/1908');
insert into autores (id, nome, nacionalidade, nascimento) values (49, 'Barbe Verey', 'Afghanistan', '24/01/1982');
insert into autores (id, nome, nacionalidade, nascimento) values (50, 'Simeon Pavlovic', 'France', '24/04/1989');
insert into autores (id, nome, nacionalidade, nascimento) values (51, 'Bill Ready', 'France', '05/02/1931');
insert into autores (id, nome, nacionalidade, nascimento) values (52, 'Yevette Fader', 'China', '04/04/1942');
insert into autores (id, nome, nacionalidade, nascimento) values (53, 'Thorn Skoughman', 'Peru', '08/11/1929');
insert into autores (id, nome, nacionalidade, nascimento) values (54, 'Cordie De Bernardis', 'Portugal', '09/03/1927');
insert into autores (id, nome, nacionalidade, nascimento) values (55, 'Cobb Trazzi', 'Guinea', '11/11/1931');
insert into autores (id, nome, nacionalidade, nascimento) values (56, 'Kelly Malicki', 'Uganda', '28/09/1982');
insert into autores (id, nome, nacionalidade, nascimento) values (57, 'Riki Turmall', 'Canada', '11/02/1975');
insert into autores (id, nome, nacionalidade, nascimento) values (58, 'Irita Gregorace', 'Indonesia', '08/10/1951');
insert into autores (id, nome, nacionalidade, nascimento) values (59, 'Arte Gomm', 'Ecuador', '14/03/1956');
insert into autores (id, nome, nacionalidade, nascimento) values (60, 'Filippa Cartledge', 'Thailand', '27/04/1948');
insert into autores (id, nome, nacionalidade, nascimento) values (61, 'Rici Imort', 'China', '23/12/1939');
insert into autores (id, nome, nacionalidade, nascimento) values (62, 'Humfrey Karolyi', 'China', '11/02/1934');
insert into autores (id, nome, nacionalidade, nascimento) values (63, 'Sargent Torry', 'Uzbekistan', '27/09/1997');
insert into autores (id, nome, nacionalidade, nascimento) values (64, 'Axe Compson', 'Philippines', '06/06/1909');
insert into autores (id, nome, nacionalidade, nascimento) values (65, 'Ruddy Sayburn', 'Japan', '18/12/1930');
insert into autores (id, nome, nacionalidade, nascimento) values (66, 'Paloma Gold', 'Philippines', '06/04/1940');
insert into autores (id, nome, nacionalidade, nascimento) values (67, 'Geoffrey Sibbson', 'South Africa', '02/11/1950');
insert into autores (id, nome, nacionalidade, nascimento) values (68, 'Obed Nare', 'Afghanistan', '07/09/1902');
insert into autores (id, nome, nacionalidade, nascimento) values (69, 'Jade Stratz', 'Czech Republic', '06/02/1909');
insert into autores (id, nome, nacionalidade, nascimento) values (70, 'Kimberlyn Serjent', 'Mexico', '20/05/1967');
insert into autores (id, nome, nacionalidade, nascimento) values (71, 'Murvyn Awdry', 'Poland', '13/05/1933');
insert into autores (id, nome, nacionalidade, nascimento) values (72, 'Caprice Cahan', 'Portugal', '14/05/1983');
insert into autores (id, nome, nacionalidade, nascimento) values (73, 'Keary Beldom', 'Philippines', '31/05/1964');
insert into autores (id, nome, nacionalidade, nascimento) values (74, 'Cross Wooffitt', 'Brazil', '26/10/1946');
insert into autores (id, nome, nacionalidade, nascimento) values (75, 'Eleanora Ferrari', 'Malaysia', '24/06/1931');
insert into autores (id, nome, nacionalidade, nascimento) values (76, 'Ashlee Swalough', 'Poland', '26/11/1949');
insert into autores (id, nome, nacionalidade, nascimento) values (77, 'Vinson Domerq', 'China', '07/07/1949');
insert into autores (id, nome, nacionalidade, nascimento) values (78, 'Renie Richold', 'China', '20/04/1902');
insert into autores (id, nome, nacionalidade, nascimento) values (79, 'Dorrie Molloy', 'Russia', '09/04/1936');
insert into autores (id, nome, nacionalidade, nascimento) values (80, 'Dorine Pendock', 'Iran', '15/09/1960');
insert into autores (id, nome, nacionalidade, nascimento) values (81, 'Danya Burwood', 'Portugal', '22/01/1971');
insert into autores (id, nome, nacionalidade, nascimento) values (82, 'Lilia Pryell', 'Mongolia', '10/12/1901');
insert into autores (id, nome, nacionalidade, nascimento) values (83, 'Kalinda Larkworthy', 'Indonesia', '02/12/1908');
insert into autores (id, nome, nacionalidade, nascimento) values (84, 'Devinne Shoreson', 'Mauritania', '02/10/1945');
insert into autores (id, nome, nacionalidade, nascimento) values (85, 'Anthony Welbeck', 'Czech Republic', '08/06/1961');
insert into autores (id, nome, nacionalidade, nascimento) values (86, 'Claudie Begwell', 'Vietnam', '08/04/1905');
insert into autores (id, nome, nacionalidade, nascimento) values (87, 'Margret Buncom', 'Saudi Arabia', '11/05/1915');
insert into autores (id, nome, nacionalidade, nascimento) values (88, 'Beaufort Scholar', 'France', '14/05/1989');
insert into autores (id, nome, nacionalidade, nascimento) values (89, 'Deanne Dabner', 'Mexico', '10/09/1990');
insert into autores (id, nome, nacionalidade, nascimento) values (90, 'Bucky Revance', 'Russia', '25/04/1925');
insert into autores (id, nome, nacionalidade, nascimento) values (91, 'Eduard Whapples', 'China', '16/03/1988');
insert into autores (id, nome, nacionalidade, nascimento) values (92, 'Vite Redfearn', 'Poland', '08/04/1932');
insert into autores (id, nome, nacionalidade, nascimento) values (93, 'Wald Ikin', 'China', '25/01/1912');
insert into autores (id, nome, nacionalidade, nascimento) values (94, 'Darci Fretson', 'Peru', '04/09/1967');
insert into autores (id, nome, nacionalidade, nascimento) values (95, 'Sonny Drewett', 'Guatemala', '06/01/1998');
insert into autores (id, nome, nacionalidade, nascimento) values (96, 'Homer Sibbald', 'Bulgaria', '04/03/1974');
insert into autores (id, nome, nacionalidade, nascimento) values (97, 'Jody Grimsell', 'France', '15/01/1958');
insert into autores (id, nome, nacionalidade, nascimento) values (98, 'Erminie Elner', 'Germany', '08/09/1994');
insert into autores (id, nome, nacionalidade, nascimento) values (99, 'Orton Crasford', 'Indonesia', '27/01/1900');
insert into autores (id, nome, nacionalidade, nascimento) values (100, 'Ervin Bortolazzi', 'Indonesia', '27/01/1948');
insert into autores (id, nome, nacionalidade, nascimento) values (101, 'Osborne Beausang', 'France', '05/05/1927');
insert into autores (id, nome, nacionalidade, nascimento) values (102, 'Dell Addicote', 'China', '04/05/1963');
insert into autores (id, nome, nacionalidade, nascimento) values (103, 'Elvina Crank', 'Yemen', '20/01/1942');
insert into autores (id, nome, nacionalidade, nascimento) values (104, 'Pace Silvester', 'United States', '24/05/1956');
insert into autores (id, nome, nacionalidade, nascimento) values (105, 'Sheilah Giannasi', 'Argentina', '30/08/1986');
insert into autores (id, nome, nacionalidade, nascimento) values (106, 'Peggi Douglas', 'Philippines', '01/02/1949');
insert into autores (id, nome, nacionalidade, nascimento) values (107, 'Carmina Christian', 'France', '07/09/1998');
insert into autores (id, nome, nacionalidade, nascimento) values (108, 'Berthe Hamly', 'Zambia', '30/07/1950');
insert into autores (id, nome, nacionalidade, nascimento) values (109, 'Kamillah Cowp', 'Peru', '29/07/1998');
insert into autores (id, nome, nacionalidade, nascimento) values (110, 'Fleur Gowers', 'Mali', '25/09/1923');
insert into autores (id, nome, nacionalidade, nascimento) values (111, 'Benedetta Morais', 'Guatemala', '16/05/1993');
insert into autores (id, nome, nacionalidade, nascimento) values (112, 'Mirella Watters', 'Comoros', '05/08/1901');
insert into autores (id, nome, nacionalidade, nascimento) values (113, 'Reidar Picton', 'Malaysia', '13/08/1982');
insert into autores (id, nome, nacionalidade, nascimento) values (114, 'Daria Howsley', 'China', '18/01/1935');
insert into autores (id, nome, nacionalidade, nascimento) values (115, 'Florida Gaymer', 'Indonesia', '15/04/1915');
insert into autores (id, nome, nacionalidade, nascimento) values (116, 'Frederich Gaisford', 'China', '26/09/1963');
insert into autores (id, nome, nacionalidade, nascimento) values (117, 'Kirsten Mattaus', 'Poland', '17/05/1999');
insert into autores (id, nome, nacionalidade, nascimento) values (118, 'Gun Acum', 'Ukraine', '15/05/1923');
insert into autores (id, nome, nacionalidade, nascimento) values (119, 'Nessy Nelius', 'Greece', '24/07/1996');
insert into autores (id, nome, nacionalidade, nascimento) values (120, 'Aguste Oswal', 'United States', '01/06/1996');
insert into autores (id, nome, nacionalidade, nascimento) values (121, 'Benny Pickerin', 'Pakistan', '02/02/1993');
insert into autores (id, nome, nacionalidade, nascimento) values (122, 'Darrel Bloxham', 'Argentina', '09/09/1998');
insert into autores (id, nome, nacionalidade, nascimento) values (123, 'Angelique Simcox', 'China', '12/04/1995');
insert into autores (id, nome, nacionalidade, nascimento) values (124, 'Liv MacTrustie', 'Sweden', '08/01/1912');
insert into autores (id, nome, nacionalidade, nascimento) values (125, 'Lyndy Arp', 'Sweden', '04/09/1910');
insert into autores (id, nome, nacionalidade, nascimento) values (126, 'Yurik O'' Cloney', 'Brazil', '28/12/1932');
insert into autores (id, nome, nacionalidade, nascimento) values (127, 'Gillie Rillatt', 'Portugal', '16/01/1915');
insert into autores (id, nome, nacionalidade, nascimento) values (128, 'Emilia Vedyashkin', 'Iran', '20/11/1997');
insert into autores (id, nome, nacionalidade, nascimento) values (129, 'Parker de Cullip', 'China', '13/02/1956');
insert into autores (id, nome, nacionalidade, nascimento) values (130, 'Lacie Seson', 'Indonesia', '26/08/1952');
insert into autores (id, nome, nacionalidade, nascimento) values (131, 'Angil Humberstone', 'Indonesia', '04/03/1925');
insert into autores (id, nome, nacionalidade, nascimento) values (132, 'Leda Gunbie', 'Russia', '17/05/1937');
insert into autores (id, nome, nacionalidade, nascimento) values (133, 'Farrah Dybell', 'Poland', '31/03/1909');
insert into autores (id, nome, nacionalidade, nascimento) values (134, 'Lon Gutteridge', 'Brazil', '06/03/1935');
insert into autores (id, nome, nacionalidade, nascimento) values (135, 'George Dyson', 'Poland', '23/03/1953');
insert into autores (id, nome, nacionalidade, nascimento) values (136, 'Tobit Shurlock', 'United States', '25/07/1992');
insert into autores (id, nome, nacionalidade, nascimento) values (137, 'Peyton Grosvener', 'Indonesia', '23/06/1906');
insert into autores (id, nome, nacionalidade, nascimento) values (138, 'Peadar Woodwind', 'Netherlands', '12/05/1978');
insert into autores (id, nome, nacionalidade, nascimento) values (139, 'Delmore Skyme', 'Indonesia', '04/11/1929');
insert into autores (id, nome, nacionalidade, nascimento) values (140, 'Wilmar Partner', 'China', '27/06/1913');
insert into autores (id, nome, nacionalidade, nascimento) values (141, 'Tatum Pasmore', 'Philippines', '11/11/1990');
insert into autores (id, nome, nacionalidade, nascimento) values (142, 'Marie-ann Kalaher', 'Philippines', '29/04/1942');
insert into autores (id, nome, nacionalidade, nascimento) values (143, 'Mickie Easthope', 'Brazil', '10/07/1964');
insert into autores (id, nome, nacionalidade, nascimento) values (144, 'Cathlene Freemantle', 'Norway', '28/06/1937');
insert into autores (id, nome, nacionalidade, nascimento) values (145, 'Jacquelin Clother', 'Afghanistan', '04/03/1977');
insert into autores (id, nome, nacionalidade, nascimento) values (146, 'Marice Overel', 'Honduras', '31/01/1974');
insert into autores (id, nome, nacionalidade, nascimento) values (147, 'Lian Aspole', 'Morocco', '03/05/1965');
insert into autores (id, nome, nacionalidade, nascimento) values (148, 'Liza Jovicic', 'China', '12/02/1969');
insert into autores (id, nome, nacionalidade, nascimento) values (149, 'Gerard Flatman', 'Ukraine', '31/03/1978');
insert into autores (id, nome, nacionalidade, nascimento) values (150, 'Willy Slinger', 'China', '01/08/1916');
insert into autores (id, nome, nacionalidade, nascimento) values (151, 'Corrie Viegas', 'China', '23/12/1968');
insert into autores (id, nome, nacionalidade, nascimento) values (152, 'Mitchael Northway', 'China', '06/01/1948');
insert into autores (id, nome, nacionalidade, nascimento) values (153, 'Vlad Syder', 'Czech Republic', '24/09/1943');
insert into autores (id, nome, nacionalidade, nascimento) values (154, 'Upton Boughton', 'Indonesia', '11/06/1957');
insert into autores (id, nome, nacionalidade, nascimento) values (155, 'Carmela Bentley', 'Brazil', '07/09/1920');
insert into autores (id, nome, nacionalidade, nascimento) values (156, 'Kameko Durie', 'Indonesia', '06/06/1941');
insert into autores (id, nome, nacionalidade, nascimento) values (157, 'Constantina Gifford', 'Indonesia', '31/03/1991');
insert into autores (id, nome, nacionalidade, nascimento) values (158, 'Kayne Miall', 'Cuba', '24/11/1980');
insert into autores (id, nome, nacionalidade, nascimento) values (159, 'Margot Bodiam', 'Poland', '17/03/1930');
insert into autores (id, nome, nacionalidade, nascimento) values (160, 'Dianemarie Glanert', 'Philippines', '24/01/1960');
insert into autores (id, nome, nacionalidade, nascimento) values (161, 'Haze Coale', 'South Africa', '24/03/1906');
insert into autores (id, nome, nacionalidade, nascimento) values (162, 'Boycey Dickman', 'Mexico', '10/12/1947');
insert into autores (id, nome, nacionalidade, nascimento) values (163, 'Marlow Bontine', 'Russia', '23/09/1934');
insert into autores (id, nome, nacionalidade, nascimento) values (164, 'Michele Haack', 'Greece', '31/03/1910');
insert into autores (id, nome, nacionalidade, nascimento) values (165, 'Maddalena Rochford', 'Poland', '16/12/1967');
insert into autores (id, nome, nacionalidade, nascimento) values (166, 'Gonzales Butten', 'Czech Republic', '25/07/1989');
insert into autores (id, nome, nacionalidade, nascimento) values (167, 'Pasquale Grute', 'Kenya', '11/07/1984');
insert into autores (id, nome, nacionalidade, nascimento) values (168, 'Way Annable', 'Poland', '15/11/1953');
insert into autores (id, nome, nacionalidade, nascimento) values (169, 'Madelon Eatttok', 'Sudan', '13/05/1982');
insert into autores (id, nome, nacionalidade, nascimento) values (170, 'Elysha Lownds', 'Finland', '11/05/1944');
insert into autores (id, nome, nacionalidade, nascimento) values (171, 'Skippie Hartless', 'Indonesia', '25/12/1986');
insert into autores (id, nome, nacionalidade, nascimento) values (172, 'Geraldine Brodnecke', 'Sweden', '01/04/1976');
insert into autores (id, nome, nacionalidade, nascimento) values (173, 'Caresa Semrad', 'Myanmar', '04/09/1932');
insert into autores (id, nome, nacionalidade, nascimento) values (174, 'Borden Raison', 'Indonesia', '18/04/1912');
insert into autores (id, nome, nacionalidade, nascimento) values (175, 'Lise Waulker', 'Croatia', '16/04/1919');
insert into autores (id, nome, nacionalidade, nascimento) values (176, 'Joann Soonhouse', 'Indonesia', '24/03/1988');
insert into autores (id, nome, nacionalidade, nascimento) values (177, 'Kaia Ebden', 'Colombia', '29/12/1984');
insert into autores (id, nome, nacionalidade, nascimento) values (178, 'Jacqui Runnacles', 'Turkmenistan', '23/08/1943');
insert into autores (id, nome, nacionalidade, nascimento) values (179, 'Shellie Gernier', 'Finland', '01/06/1920');
insert into autores (id, nome, nacionalidade, nascimento) values (180, 'Wyatan Barbie', 'Ethiopia', '06/12/1984');
insert into autores (id, nome, nacionalidade, nascimento) values (181, 'Caddric Learmonth', 'Indonesia', '20/12/1937');
insert into autores (id, nome, nacionalidade, nascimento) values (182, 'Norton Deakan', 'Greece', '11/11/1982');
insert into autores (id, nome, nacionalidade, nascimento) values (183, 'Cherianne Durnall', 'Poland', '13/03/1975');
insert into autores (id, nome, nacionalidade, nascimento) values (184, 'Yettie Maccaig', 'Aland Islands', '24/09/1977');
insert into autores (id, nome, nacionalidade, nascimento) values (185, 'Ned Cashford', 'Ukraine', '30/03/1996');
insert into autores (id, nome, nacionalidade, nascimento) values (186, 'Kenyon Jobson', 'Philippines', '13/10/1923');
insert into autores (id, nome, nacionalidade, nascimento) values (187, 'Magdaia Gouldstraw', 'China', '04/07/1990');
insert into autores (id, nome, nacionalidade, nascimento) values (188, 'Blithe Cracknell', 'Ireland', '01/10/1942');
insert into autores (id, nome, nacionalidade, nascimento) values (189, 'Ax Mennell', 'China', '01/01/1925');
insert into autores (id, nome, nacionalidade, nascimento) values (190, 'Feodor Chellingworth', 'Indonesia', '26/07/1932');
insert into autores (id, nome, nacionalidade, nascimento) values (191, 'Franz Klimmek', 'Russia', '03/04/1998');
insert into autores (id, nome, nacionalidade, nascimento) values (192, 'Krystal Tolliday', 'China', '01/01/1971');
insert into autores (id, nome, nacionalidade, nascimento) values (193, 'Alaric Jones', 'China', '10/10/1981');
insert into autores (id, nome, nacionalidade, nascimento) values (194, 'Carmine Wilcott', 'U.S. Virgin Islands', '22/05/1978');
insert into autores (id, nome, nacionalidade, nascimento) values (195, 'Hattie Colledge', 'Portugal', '03/09/1954');
insert into autores (id, nome, nacionalidade, nascimento) values (196, 'Gilberto Gavrieli', 'Portugal', '07/02/1986');
insert into autores (id, nome, nacionalidade, nascimento) values (197, 'Ram Grayshon', 'Ukraine', '21/01/1981');
insert into autores (id, nome, nacionalidade, nascimento) values (198, 'Lindsey Dunkerton', 'Indonesia', '01/06/1982');
insert into autores (id, nome, nacionalidade, nascimento) values (199, 'Ephraim Chidwick', 'Ukraine', '01/07/1932');
insert into autores (id, nome, nacionalidade, nascimento) values (200, 'Edmon Donkersley', 'Botswana', '14/10/1923');
