insert into autores (id, nome, nacionalidade, nascimento) values (1, 'Aubrette', 'Jefferson City', '9/10/1972');
insert into autores (id, nome, nacionalidade, nascimento) values (2, 'Fax', 'Shewopo', '1/7/1984');
insert into autores (id, nome, nacionalidade, nascimento) values (3, 'Timothee', 'Las Mercedes', '4/20/1970');
insert into autores (id, nome, nacionalidade, nascimento) values (4, 'Noellyn', 'Jianlong', '3/17/1989');
insert into autores (id, nome, nacionalidade, nascimento) values (5, 'Iggy', 'Borzytuchom', '11/2/1993');
insert into autores (id, nome, nacionalidade, nascimento) values (6, 'Barton', 'Wansheng', '11/23/1969');
insert into autores (id, nome, nacionalidade, nascimento) values (7, 'Mikael', 'Skoura', '6/29/1977');
insert into autores (id, nome, nacionalidade, nascimento) values (8, 'Cleo', 'Campo Largo', '1/9/1979');
insert into autores (id, nome, nacionalidade, nascimento) values (9, 'Chico', 'Zykovo', '7/22/1976');
insert into autores (id, nome, nacionalidade, nascimento) values (10, 'Duke', 'Klishkivtsi', '7/3/1969');
insert into autores (id, nome, nacionalidade, nascimento) values (11, 'Renato', 'Dinalongan', '4/30/1997');
insert into autores (id, nome, nacionalidade, nascimento) values (12, 'Cordey', 'Viso', '7/5/1999');
insert into autores (id, nome, nacionalidade, nascimento) values (13, 'Gussi', 'Tarakaniv', '12/25/1984');
insert into autores (id, nome, nacionalidade, nascimento) values (14, 'Leontine', 'Labao', '10/1/1994');
insert into autores (id, nome, nacionalidade, nascimento) values (15, 'Ulla', 'Masparrito', '12/29/1987');
insert into autores (id, nome, nacionalidade, nascimento) values (16, 'Urson', 'Granja do Tedo', '7/18/1982');
insert into autores (id, nome, nacionalidade, nascimento) values (17, 'Abba', 'Chelbasskaya', '11/10/1974');
insert into autores (id, nome, nacionalidade, nascimento) values (18, 'Deidre', 'Gzy', '3/23/1989');
insert into autores (id, nome, nacionalidade, nascimento) values (19, 'Garnette', 'Zhangbei', '3/14/1965');
insert into autores (id, nome, nacionalidade, nascimento) values (20, 'Camilla', 'Saint-Lô', '9/26/1986');
